config_from_cf:
  cf_deployment_name: (( name ))
  cf_director_uuid: (( director_uuid ))
  nats:
    user: (( properties.nats.user ))
    password: (( properties.nats.password ))
    port: (( properties.nats.port ))
    machines: (( properties.nats.machines ))
  domain: (( properties.domain ))
  system_domain: (( properties.system_domain ))
  app_domains: (( properties.app_domains ))
  api_url: (( "https://api." properties.domain ))
  skip_ssl_validation: (( properties.skip_ssl_validation ))
  admin_username: (( properties.admin_username ))
  admin_password: (( properties.admin_password ))
  smoke_tests:
    use_existing_org: (( properties.smoke_tests.use_existing_org ))
    org: (( properties.smoke_tests.org ))
  consul:
    datacenter: (( properties.consul.agent.datacenter ))
    domain: (( properties.consul.agent.domain ))
    log_level: (( properties.consul.agent.log_level ))
    lan_servers: (( properties.consul.agent.servers.lan ))
    ca_cert: (( properties.consul.ca_cert ))
    agent_cert: (( properties.consul.agent_cert ))
    agent_key: (( properties.consul.agent_key ))
    encrypt_keys: (( properties.consul.encrypt_keys ))
    server_cert: (( properties.consul.server_cert ))
    server_key: (( properties.consul.server_key ))

# The keys below should not be included in the final stub
name: (( merge ))
director_uuid: (( merge ))
properties:
  nats:
    user: (( merge ))
    password: (( merge ))
    machines: (( merge ))
    port: (( merge ))
  domain: (( merge ))
  system_domain: (( merge ))
  app_domains: (( merge ))
  admin_username: (( merge ))
  admin_password: (( merge ))
  skip_ssl_validation: (( merge || nil ))
  smoke_tests:
    use_existing_org: (( merge || nil ))
    org: (( merge || nil ))
  consul:
    agent:
      domain: (( merge ))
      log_level: (( merge ))
      datacenter: (( merge || nil ))
      servers:
        lan: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
