name: cf-mysql

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: cf-mysql
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 2
  azs: [z1, z2]
  networks:
  - name: default
  vm_type: default
  stemcell: default
  persistent_disk_type: large
  jobs:
  - {release: cf-mysql, name: mysql}

- name: arbitrator
  instances: 1
  azs: [z3]
  networks:
  - name: default
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: arbitrator}

- name: proxy
  instances: 2
  azs: [z1,z2]
  networks:
  - name: default
    static_ips:
    - 10.244.7.3
    - 10.244.8.3
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: proxy}

- name: bootstrap
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: bootstrap}

- name: rejoin-unsafe
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: rejoin-unsafe}

- name: verify-cluster-schemas
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: verify-cluster-schemas}

properties:
  cf_mysql:
    mysql:
      admin_password: ((cf_mysql_mysql_admin_password))
      cluster_health:
        password: ((cf_mysql_mysql_cluster_health_password))
      galera_healthcheck:
        db_password: ((cf_mysql_mysql_galera_healthcheck_db_password))
        endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
      persistent_disk: 100000
      roadmin_password: ((cf_mysql_mysql_roadmin_password))
    proxy:
      api_password: ((cf_mysql_proxy_api_password))
    standalone: true

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_db_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
- name: cf_mysql_mysql_roadmin_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password
